backports: Samsung drivers should depend on recent kernel
The Samsung regulator drivers are using a new struct member.
This fixes this compile error:

/drivers/regulator/s2mps11.c: In function ‘s2mps11_pmic_probe’:
/drivers/regulator/s2mps11.c:441:23: error: ‘struct sec_pmic_dev’ has no member named ‘regmap_pmic’
make[6]: *** [/home/hauke/compat-wireless/tmp/drivers/regulator/s2mps11.o] Error 1
make[5]: *** [/home/hauke/compat-wireless/tmp/drivers/regulator] Error 2

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>