backport: fix the backported led_classdev struct
In leds-disabled.h, if any of the three LED flags is disabled in
.config (i.e. NEW_LEDS, LEDS_CLASS or LEDS_TRIGGERS), a dummy struct
is added.  The problem is that this structure doesn't seem to have
been updated in a while and, if LEDS_TRIGGERS is not defined, we would
get the following errors:

/home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c:23:5: error: conflicting types for ‘backport_led_set_brightness_sync’
 int led_set_brightness_sync(struct led_classdev *led_cdev,
     ^
In file included from /home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c:11:0:
/home/luca/iwlwifi/iwlwifi-stack-dev/backport-include/linux/leds.h:55:12: note: previous declaration of ‘backport_led_set_brightness_sync’ was here
 extern int led_set_brightness_sync(struct led_classdev *led_cdev,
            ^
/home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c: In function ‘backport_led_set_brightness_sync’:
/home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c:29:143: warning: comparison of distinct pointer types lacks a cast
/home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c:34:14: error: ‘struct backport_led_classdev’ has no member named ‘brightness_set_sync’
  if (led_cdev->brightness_set_sync)
              ^
/home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c:35:18: error: ‘struct backport_led_classdev’ has no member named ‘brightness_set_sync’
   return led_cdev->brightness_set_sync(led_cdev,
                  ^
/home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c: At top level:
/home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c:39:49: error: conflicting types for ‘backport_led_set_brightness_sync’
In file included from /home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.c:11:0:
/home/luca/iwlwifi/iwlwifi-stack-dev/backport-include/linux/leds.h:55:12: note: previous declaration of ‘backport_led_set_brightness_sync’ was here
 extern int led_set_brightness_sync(struct led_classdev *led_cdev,
            ^
scripts/Makefile.build:258: recipe for target '/home/luca/iwlwifi/iwlwifi-stack-dev/compat/backport-4.5.o' failed

To fix this, update the structure accordingly.

Signed-off-by: Luca Coelho <luciano.coelho@intel.com>
Signed-off-by: Johannes Berg <johannes.berg@intel.com>