backports: add missing linux/mm.h to airspy
Without this patch I get the following error message when compiling
against kernel 3.2, all other kernel versions work:

3.2.60/drivers/media/usb/airspy/airspy.c: In function ‘airspy_queue_setup’:
3.2.60/drivers/media/usb/airspy/airspy.c:506:2: error: implicit declaration of function ‘PAGE_ALIGN’ [-Werror=implicit-function-declaration]
sizes[0] = PAGE_ALIGN(s->buffersize);

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>