backports: irq_get_trigger_type requires CONFIG_HAVE_GENERIC_HARDIRQS=y
Only backport irq_get_trigger_type on architectures that have
CONFIG_HAVE_GENERIC_HARDIRQS=y. Otherwise we end up with:

In file included from drivers/pci/msi.c:11:0:
backport/backport-include/linux/irq.h: In function 'irq_get_trigger_type':
backport/backport-include/linux/irq.h:9:9: error: implicit declaration
of function 'irq_get_irq_data' [-Werror=implicit-function-declaration]
  struct irq_data *d = irq_get_irq_data(irq);

Signed-off-by: Stefan Assmann <sassmann@kpanic.de>
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>