backports: bump minimum kernel version for ADV7604 to 3.13
While doing a make allmodconfig I noticed the following:
  CC [M]  /dev/shm/backports-next/drivers/media/i2c/adv7604.o
/dev/shm/backports-next/drivers/media/i2c/adv7604.c:31:33: fatal error: linux/gpio/consumer.h: No such file or directory

linux/gpio/consumer.h cannot be backported currently, as functions rely
on in-kernel functionality (GPIO_DEVRES). Bumping the minimum required
kernel version for ADV7604 to 3.13 where the header got introduced.

Signed-off-by: Stefan Assmann <sassmann@kpanic.de>
[add comment with reason]
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>