backports: fix mconf compilation library assumptions
On OpenSUSE factory 'make menuconfig' fails to compile with:

cc -Wall -Wmissing-prototypes -Wstrict-prototypes -O2
-fomit-frame-pointer -DCURSES_LOC="<ncurses.h>" -DLOCALE   -c -o
lxdialog/yesno.o lxdialog/yesno.c
cc -Wl,--no-as-needed -lncursesw  mconf.o zconf.tab.o
lxdialog/checklist.o lxdialog/inputbox.o lxdialog/menubox.o
lxdialog/textbox.o lxdialog/util.o lxdialog/yesno.o   -o mconf
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld:
/lib64/libncursesw.so.5: undefined reference to symbol 'acs_map'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libtinfo.so:
error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Although this can be fixed by linking with -ltinfo after a bit
further investigation I've traced this issue down to how we speak
to the linker and ask it to link and when. For instance if one
were to compile and link mconf by specifying the linker requirements
before the final object file things fail and if we ask for it after
things work. For instance if we ask for the libraries before:

gcc  -lncursesw -o
	kconf/mconf
	kconf/mconf.o
	kconf/zconf.tab.o
	kconf/lxdialog/checklist.o
	kconf/lxdialog/util.o
	kconf/lxdialog/inputbox.o
	kconf/lxdialog/textbox.o
	kconf/lxdialog/yesno.o
	kconf/lxdialog/menubox.o  -lncursesw

Passing the linker requirements at the end makes the gcc happy:

gcc  -o kconf/mconf
	kconf/mconf.o
	kconf/zconf.tab.o
	kconf/lxdialog/checklist.o
	kconf/lxdialog/util.o
	kconf/lxdialog/inputbox.o
	kconf/lxdialog/textbox.o
	kconf/lxdialog/yesno.o
	kconf/lxdialog/menubox.o  -lncursesw

It seems that using -Wl,--no-as-needed does not do what we wish with regards
to the above requirements, this could be a bug but the kernel treats things
a bit differently so we need to adopt, fix this by being explicit by
using -Wl,--add-needed and letting it figure things out automagically.

This has been tested on Debian and OpenSUSE factory.

Signed-off-by: Luis R. Rodriguez <mcgrof@suse.com>